import type { Beach } from "./types";

/**
 * HRM supervised beaches.
 *
 * Names are the real 19 supervised beaches from Halifax's ArcGIS open data set.
 * Coordinates are approximate (good enough to place each dot on the right lake).
 * Statuses, reasons and water quality values here are sample data for building
 * and styling the site. A later phase wires these to the live daily source.
 */
export const BEACHES: Beach[] = [
  {
    id: "chocolate-lake",
    name: "Chocolate Lake Beach",
    location: "Chocolate Lake, Halifax",
    lat: 44.636,
    lng: -63.61,
    status: "risk",
    reason:
      "Blue green algae bloom observed. Keep children and dogs out of the water.",
    waterQuality: "Algae advisory. Bacteria within guideline (E. coli 12 CFU/100mL).",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "kidston-lake",
    name: "Kidston Lake Beach",
    location: "Kidston Lake, Spryfield, Halifax",
    lat: 44.618,
    lng: -63.641,
    status: "closed",
    reason:
      "Bacteria (E. coli) went past the safe guideline in this morning's sample.",
    waterQuality: "E. coli 340 CFU/100mL, above the 200 guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "birch-cove",
    name: "Birch Cove Beach",
    location: "Lake Banook, Dartmouth",
    lat: 44.683,
    lng: -63.572,
    status: "risk",
    reason:
      "Blue green algae advisory in effect. Avoid contact and do not let dogs drink the water.",
    waterQuality: "Algae advisory. Enterococci within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "lake-echo",
    name: "Lake Echo Beach",
    location: "Lake Echo",
    lat: 44.728,
    lng: -63.382,
    status: "closed",
    reason: "Elevated bacteria levels. Beach closed until the next clear sample.",
    waterQuality: "Enterococci 88 CFU/100mL, above the 70 guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "penhorn-lake",
    name: "Penhorn Lake Beach",
    location: "Penhorn Lake, Dartmouth",
    lat: 44.666,
    lng: -63.532,
    status: "risk",
    reason: "Possible algae bloom reported. Sampling underway, please use caution.",
    waterQuality: "Under review, awaiting a confirmation sample.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "albro-lake",
    name: "Albro Lake Beach",
    location: "Albro Lake, Dartmouth",
    lat: 44.682,
    lng: -63.568,
    status: "open",
    waterQuality: "E. coli 8 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to August 31",
    waterType: "Fresh water",
  },
  {
    id: "springfield",
    name: "Springfield Beach",
    location: "Springfield Lake, Middle Sackville",
    lat: 44.776,
    lng: -63.705,
    status: "open",
    waterQuality: "E. coli 6 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "petpeswick",
    name: "Petpeswick Beach",
    location: "Petpeswick Lake, Musquodoboit Harbour",
    lat: 44.795,
    lng: -63.14,
    status: "open",
    waterQuality: "Enterococci 10 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "campbell-point",
    name: "Campbell Point Beach",
    location: "Hatchet Lake, Halifax",
    lat: 44.596,
    lng: -63.702,
    status: "open",
    waterQuality: "E. coli 14 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "fenerty",
    name: "Fenerty Beach",
    location: "First Lake, Lower Sackville",
    lat: 44.772,
    lng: -63.682,
    status: "open",
    waterQuality: "E. coli 5 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "malay-falls",
    name: "Malay Falls Beach",
    location: "Malay Falls, Eastern Shore",
    lat: 44.895,
    lng: -62.53,
    status: "open",
    waterQuality: "E. coli 18 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "saunders",
    name: "Saunders Beach",
    location: "Grand Lake, Halifax",
    lat: 44.83,
    lng: -63.53,
    status: "open",
    waterQuality: "Enterococci 9 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "webbers",
    name: "Webber's Beach",
    location: "Porters Lake, Halifax",
    lat: 44.74,
    lng: -63.3,
    status: "open",
    waterQuality: "E. coli 11 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "kinap",
    name: "Kinap Beach",
    location: "Grand Lake, Halifax",
    lat: 44.81,
    lng: -63.56,
    status: "open",
    waterQuality: "E. coli 7 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "sandy-lake",
    name: "Sandy Lake Beach",
    location: "Sandy Lake, Bedford",
    lat: 44.735,
    lng: -63.665,
    status: "open",
    waterQuality: "E. coli 13 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "shubie-park",
    name: "Shubie Park Beach",
    location: "Lake Charles, Dartmouth",
    lat: 44.733,
    lng: -63.545,
    status: "open",
    waterQuality: "Enterococci 12 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "long-pond",
    name: "Long Pond Beach",
    location: "Long Pond, Halifax",
    lat: 44.63,
    lng: -63.618,
    status: "open",
    waterQuality: "E. coli 9 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "cunard-lake",
    name: "Cunard Pond Beach",
    location: "Williams Lake, Halifax",
    lat: 44.61,
    lng: -63.592,
    status: "open",
    waterQuality: "E. coli 10 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
  {
    id: "kearney-lake",
    name: "Kearney Lake Beach",
    location: "Kearney Lake, Halifax",
    lat: 44.69,
    lng: -63.672,
    status: "open",
    waterQuality: "E. coli 15 CFU/100mL, within guideline.",
    lifeguardSupervision: "July 1 to September 1",
    waterType: "Fresh water",
  },
];
